apiVersion: v1
kind: Service
metadata:
  name: detyrekursi-svc2
spec:
  selector:
    app: detyrekursi
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8080
  type: NodePort

  #kubectl apply -f app-service2.yaml 